<?php

namespace Scandio\Bundle\FireStarterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getUncategorized()
    {
        return $this->createQueryBuilder('l')
            ->where('l.tile IS NULL')
            ->orderBy('l.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
