<?php

namespace Scandio\Bundle\FireStarterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * @param Link $link
     * @param $tagName
     */
    public function add(Link $link, $tagName)
    {
        $tag = $this->find($tagName);
        if (!$tag instanceof Tag) {
            $tag = new Tag();
        }

        $tag->setName($tagName);

        $em = $this->getEntityManager();
        $em->persist($tag);

        $link->addTag($tag);
        $em->persist($link);
        $em->flush();
    }

    /**
     * @return array
     */
    public function getAll()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.name')
            ->getQuery()
            ->getResult();
    }
}
